# -*- coding: utf-8 -*-
import json, collections, html, datetime
d=json.load(open('data/story.json',encoding='utf-8'))
crown=d['stories']['crown']; wp=crown['waypoints']
caplabels=crown.get('capLabels',{}); voices=d.get('voices',{})

def cond(when):
    if not when: return None
    if when.get('default'): return "DEFAULT (otherwise)"
    parts=[]
    for k in when.get('allTrue',[]): parts.append(k)
    for k in when.get('allFalse',[]): parts.append("NOT "+k)
    for k in when.get('anyTrue',[]): parts.append("any: "+k)
    for k in when.get('anyFalse',[]): parts.append("any NOT: "+k)
    for k,v in (when.get('equals') or {}).items(): parts.append("%s = %s"%(k,v))
    for k,v in (when.get('notEquals') or {}).items(): parts.append("%s ≠ %s"%(k,v))
    return " AND ".join(parts) if parts else "?"

def flagstr(sf):
    if not sf: return None
    return ", ".join("%s=%s"%(k,json.dumps(v) if isinstance(v,str) else str(v).lower()) for k,v in sf.items())

def is_stub(t): return bool(t) and "PAWN — not yet written" in t
def unreachable_note(when):
    if when and 'timid' in (when.get('allTrue') or []) and 'fox_ally' in (when.get('allFalse') or []):
        return "currently UNREACHABLE — `timid` is only set on the unmarked cemetery path, so the fox is always alive there"
    return None

out=[]
def w(s=""): out.append(s)

w("# The Crown of the Mushroom King — Full Story Script")
w()
w("_Auto-generated from `data/story.json` (story version %s). Do not edit this file by hand — regenerate with `python3 tools/gen-script.py`._  "%d['meta'].get('version'))
w()
w("This is the complete text of every waypoint, scene, choice, and ending — all branches shown together (the app shows only one per walk). Conditions in **_when:_** lines decide which scene/variant a given walker sees.")
w()
# legend
w("**Legend** — `→` routes to the next post/beat · _sets:_ flags written · _gains:_ collectible · ★/✦ good ending · 🩸 dark ending · ❄ bleak ending · ⚠️ stub or unreachable.")
w()
# flag glossary
w("## Flags")
w()
for k,v in (d.get('flagNotes') or {}).items():
    w("- **`%s`** — %s"%(k, v))
w()
w("_All flags:_ " + ", ".join("`%s`"%f for f in d.get('flags',[])))
w()
w("---")
w()

def render_narration(o, indent=""):
    """Render every narration part of a scene/waypoint dict, all branches."""
    L=[]
    if o.get('text'): L.append(("",o['text']))
    if o.get('seasonalIntro'):
        for s in o['seasonalIntro']:
            L.append(("_Seasonal — %s:_ "%s.get('when'), s.get('text','')))
    if o.get('textCont'): L.append(("",o['textCont']))
    if o.get('variants'):
        for v in o['variants']:
            tag="_Variant (%s):_ "%(cond(v.get('when')) or 'default')
            L.append((tag, v.get('text','')))
    out_lines=[]
    for tag,txt in L:
        if not txt: continue
        for i,para in enumerate(txt.split("\n\n")):
            out_lines.append(indent + (tag if i==0 else "") + para)
    return out_lines

def render_ending(e, indent=""):
    note=e.get('note','(ending)'); tone=e.get('tone','')
    w(indent+"**ENDING: %s** %s"%(note, ("· _%s_"%tone if tone else "")))
    for ex in e.get('exits',[]):
        bits=[]
        if ex.get('next'): bits.append("→ `%s`"%ex['next'])
        if ex.get('commit'): bits.append("→ commit/continue")
        lab=ex.get('label','(exit)')
        w(indent+"  - _exit:_ **“%s”** %s"%(lab, " ".join(bits)))
        if ex.get('reveal'):
            for para in ex['reveal'].split("\n\n"):
                w(indent+"    > "+para)
    if not e.get('exits'):
        w(indent+"  - _(terminal — “Walk it again”)_")

def render_choices(o):
    if not o.get('choices'): return
    if o.get('prompt'): w("**Choice — “%s”**"%o['prompt'])
    else: w("**Choice:**")
    w()
    for i,c in enumerate(o['choices'],1):
        meta=[]
        sf=flagstr(c.get('setFlags'))
        if sf: meta.append("_sets:_ %s"%sf)
        if c.get('collect'): meta.append("_gains:_ %s"%caplabels.get(c['collect'],c['collect']))
        if c.get('retry'): meta.append("_wrong answer → flare + hint (never advances)_")
        if c.get('next'): meta.append("→ `%s`"%c['next'])
        if c.get('ending'): meta.append("→ ending")
        if (not c.get('next')) and (not c.get('ending')) and (not c.get('retry')) and o.get('next'):
            meta.append("→ `%s`"%o['next'])
        w("%d. **“%s”**%s"%(i, c['label'], ("  ·  "+"  ·  ".join(meta) if meta else "")))
        if c.get('text'):
            for para in c['text'].split("\n\n"):
                w("   "+para)
        if c.get('hints'):
            for j,h in enumerate(c['hints'],1):
                w("   - _hint %d:_ %s"%(j,h))
        if c.get('ending'):
            render_ending(c['ending'], "   ")
        w()

def render_scene_body(o):
    for line in render_narration(o):
        w(line); w()
    # endingVariants (each is an ending leaf)
    if o.get('endingVariants'):
        w("**Endings (one is chosen by state):**"); w()
        for ev in o['endingVariants']:
            cn=cond(ev.get('when')) or 'default'
            ur=unreachable_note(ev.get('when'))
            hdr="_when:_ %s"%cn + (" — ⚠️ %s"%ur if ur else "")
            w(hdr)
            for para in (ev.get('text') or '').split("\n\n"):
                if para: w("> "+para)
            if ev.get('ending'): render_ending(ev['ending'])
            w()
    render_choices(o)
    # scene-level terminal ending / end
    if o.get('ending'): render_ending(o['ending'])
    if o.get('end'): w("**ENDING: %s** _(terminal)_"%o.get('endNote','The End'))
    # routing if linear (no choices/endings)
    if o.get('next') and not o.get('choices') and not o.get('endingVariants') and not o.get('ending'):
        w("→ continues to `%s`"%o['next'])
        w()

for wid, node in wp.items():
    n=node.get('n'); tag=node.get('tag'); title=node.get('title','')
    hdr="## "
    if n: hdr+="Post %s — "%n
    hdr+="%s  `#crown/%s`"%(title, wid)
    w(hdr)
    sub=[]
    if tag: sub.append(tag)
    if node.get('gateless'): sub.append("_(no QR — in-app “Walk on” beat)_")
    if node.get('collectLabel'): sub.append("awards **%s**"%node['collectLabel'])
    if node.get('image'): sub.append("img: `%s`"%node['image'])
    if sub: w(" · ".join(sub)); w()
    bsf=flagstr(node.get('setFlags'))
    if bsf: w("_On arrival sets:_ %s"%bsf); w()
    if node.get('buildNote'): w("> **BUILD NOTE:** %s"%node['buildNote']); w()
    if node.get('scenes'):
        # Waypoint-level narration (text / seasonalIntro / textCont / variants) renders
        # at runtime BEFORE each scene's own content (a scene may override a field —
        # e.g. its own seasonalIntro). Print it once here so the script is complete.
        if any(node.get(k) for k in ('text','seasonalIntro','textCont','variants')):
            w("_Shared narration — rendered first for every scene below (a scene may override a part of it):_")
            w()
            for line in render_narration(node): w(line); w()
        for si,sc in enumerate(node['scenes']):
            cn=cond(sc.get('when')) or 'default'
            stub=is_stub(sc.get('text'))
            mark=" — ⚠️ STUB (not yet written)" if stub else ""
            # rugged pawn stubs are also currently unreachable (rugged = always Hero)
            if stub and wid.startswith('r') and sc.get('when',{}).get('equals',{}).get('road')=='pawn':
                mark=" — ⚠️ STUB & currently unreachable (the rugged arm is always Hero)"
            vc=sc.get('voice')
            w("### Scene %d — _when:_ %s%s"%(si+1, cn, mark))
            if vc and voices.get(vc): w("_Voice:_ %s"%voices[vc])
            scf=flagstr(sc.get('setFlags'))
            if scf: w("_On entry sets:_ %s"%scf)
            w()
            render_scene_body(sc)
            w()
    else:
        vc=node.get('voice')
        if vc and voices.get(vc): w("_Voice:_ %s"%voices[vc]); w()
        render_scene_body(node)
    w("---"); w()

open('story-script.md','w',encoding='utf-8').write("\n".join(out)+"\n")
print("wrote story-script.md (%d lines)"%len(out))
